import React from 'react';
import { ErrorBoundary as ReactErrorBoundary } from 'react-error-boundary';
import { useNetwork } from '../../context/NetwokrContext';

const ErrorFallback = ({ error, resetErrorBoundary }: { error: Error, resetErrorBoundary: () => void }) => {
  return (
    <div role="alert">
      <p>Something went wrong:</p>
      <pre>{error.message}</pre>
      <button onClick={resetErrorBoundary}>Try again</button>
    </div>
  );
};

const ErrorBoundary: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  
  const { nodes, edges } = useNetwork();
    
  const handleError = (error: Error) => {
    console.error("Uncaught error:", error);
    saveGraph(); // Llama a la funciÃ³n saveGraph para guardar la red
  };

  const saveGraph = () => {
    let saveNodes = nodes.get();
    let saveEdges = edges.get();
    const json = JSON.stringify({ nodes: saveNodes, edges: saveEdges }, null, 2);
    const blob = new Blob([json], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = 'graph.json';
    a.click();
    URL.revokeObjectURL(url);
};

  return (
    <ReactErrorBoundary
      FallbackComponent={ErrorFallback}
      onError={handleError}
    >
      {children}
    </ReactErrorBoundary>
  );
};

export default ErrorBoundary;